# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'EventGoS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'AFNetworking', '~> 3.1'
  pod 'MBProgressHUD', '~> 1.0'
  pod 'Firebase/Core'
  pod 'Firebase/AdMob'
  pod 'Firebase/Crash'
  pod 'Firebase/Storage'
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'
  pod 'GoogleMaps'
  pod 'AnimatedTextInput', '~> 0.4'
  pod 'ChameleonFramework', '~> 2.1'
  pod 'SwiftyJSON'
  pod 'AnimatedTextInput', '~> 0.4'
  pod 'DKImagePickerController'
  pod 'AlamofireImage', '~> 3.1'
  pod 'SnapKit', '~> 3.2.0'
  pod 'RxSwift',    '~> 3.0'
  pod 'RxCocoa',    '~> 3.0'
  pod 'Validator', '~> 2.1'
  # Pods for EventGoS

end
